### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Axkaban** [agrajalesh/f1-3-c2p1-colmar-academy#2]
Nice work implementing global styles: [https://github.com/agrajalesh/f1-3-c2p1-colmar-academy/blob/master/colmar%20academy%20project/resources/css/style.css#L1-L15](https://github.com/agrajalesh/f1-3-c2p1-colmar-academy/blob/master/colmar%20academy%20project/resources/css/style.css#L1-L15)

Thanks again for comments: [https://github.com/agrajalesh/f1-3-c2p1-colmar-academy/blob/master/colmar%20academy%20project/resources/css/style.css#L16](https://github.com/agrajalesh/f1-3-c2p1-colmar-academy/blob/master/colmar%20academy%20project/resources/css/style.css#L16)

Very interesting approach with the media queries: 
[https://github.com/agrajalesh/f1-3-c2p1-colmar-academy/blob/master/colmar%20academy%20project/resources/css/style.css#L81](https://github.com/agrajalesh/f1-3-c2p1-colmar-academy/blob/master/colmar%20academy%20project/resources/css/style.css#L81)

it seems that is necessary to establish fixed measurements like `px` instead of responsive ones like `em`s. When I play with inspect on mobile sizes, the menu icons didn't show up, like when I shrink browser, and the regular text letters go bananas!
![screen shot 2018-02-07 at 12 10 17 am](https://user-images.githubusercontent.com/24210280/35899990-88edd5d0-0b9d-11e8-93bf-0541ed89e4cc.png)
I really believe that it is because of the intent for responsiveness in media queries. No big deal though. Just no mobile visibility

**Comment by agrajalesh** [comment]
Ok Thanks. I will check it.
