### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [agrajalesh/f1-3-c2p1-colmar-academy#3]
200 OK Pass!

Congratulations, you have completed the project with a passing grade. You just might to have to adjust your media queries, and since you are at it, you might like to start on the mobile first mindset. Your general styles will be though of with mobile devices in mind, and start enlarging and adjusting everything as we go through media queries for larger sizes until the browser is in full size. 

Great job!

Good luck!

**Comment by agrajalesh** [comment]
Thanks for yours comments and advice. I will reviewed the media queries of the project. You are right. I made the design of the program on the contrary, starting from the biggest to the smallest. I will correct it.

**Comment by Axkaban** [comment]
You do not have to change it, those are actual styles, some companies do develop desktop first because they know that is the main method people will search for them, on the other hand you also have companies that develop mobile first, because the are aware that their target audience comes from all devices but most commonly on mobile phone. Having accessibility in mind is mainly your first goal, answering the question: what’s your target audience?

**Comment by agrajalesh** [comment]
Thanks for the explanation.
 The target people is the most important thing. I agree.
Regards
Alberto


2018-02-08 9:51 GMT-05:00 Axel kaban <notifications@github.com>:
